repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py313-plus]
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: ["--target-version", "py313"]
  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#flake8
        # E203 Whitespace before ':'
        # E501 line too long
        # E704 Multiple statements on one line (def)
        args: ["--extend-ignore", "E203 E501 E704"]
  - repo: https://github.com/djlint/djLint
    rev: v1.40.3
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
